// storage names
const ACCESS_TOKEN_STORAGE_NAME = 'access_token';
const DEVICE_ID_STORAGE_NAME = 'playerID';
const VOIP_TOKEN_STORAGE_NAME = 'voIPToken';
const USER_ID_STORAGE_NAME = 'user_id';
const USER_STORAGE_NAME = 'user';
const FIRST_OPEN_APP = 'first_open_app';
const MODE_STORAGE_NAME = 'mode';

// app redirects
const APP_AUTH_REDIRECT_URL = '/auth';
const APP_HOME_REDIRECT_URL = '/home';

export {
  FIRST_OPEN_APP,
  ACCESS_TOKEN_STORAGE_NAME,
  DEVICE_ID_STORAGE_NAME,
  VOIP_TOKEN_STORAGE_NAME,
  USER_ID_STORAGE_NAME,
  USER_STORAGE_NAME,
  MODE_STORAGE_NAME,
  APP_AUTH_REDIRECT_URL,
  APP_HOME_REDIRECT_URL,
};
